# -*- coding: utf-8 -*-
"""Previsao_clima.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/162XLQMpo5nRaScthPWs0mjTCeTjeW3aZ
"""

import pandas as pd
energy_dataset = pd.read_csv('https://raw.githubusercontent.com/Borgarelli/IAHourly_energy_demand_generation_weather/main/energy_dataset.csv')
energy_dataset.head()

weather_features = pd.read_csv('https://raw.githubusercontent.com/Borgarelli/IAHourly_energy_demand_generation_weather/main/weather_features.csv')
weather_features.head()